# Generated by Django 3.1.4 on 2021-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_place', models.CharField(max_length=200)),
                ('issue_desc', models.CharField(max_length=200)),
                ('issue_period', models.IntegerField()),
            ],
        ),
    ]
