# Generated by Django 3.1.4 on 2021-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_issue_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_image',
            field=models.CharField(default='https://www.wbcsd.org/var/site/storage/images/media/images/the-alliance-to-end-plastic-waste/128787-1-eng-GB/The-Alliance-to-End-Plastic-Waste_i1140.jpg', max_length=500),
        ),
    ]
